services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: template_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d template_app"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: docker/back.Dockerfile
    restart: unless-stopped
    # Read environment variables from .env file
    env_file:
      - back/.env
    ports:
      - "8001:8001"
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local
