"""initial

Revision ID: 1a6d72548d3a
Revises:
Create Date: 2025-10-05 01:08:40.949633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1a6d72548d3a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "band",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "genre",
            sa.Enum(
                "ROCK",
                "POP",
                "JAZZ",
                "BLUES",
                "FOLK",
                "ELECTRONIC",
                "HIP_HOP",
                name="musicgenre",
            ),
            nullable=False,
        ),
        sa.Column("formed_year", sa.Integer(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_band_name"), "band", ["name"], unique=True)
    op.create_table(
        "musician",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_musician_name"), "musician", ["name"], unique=False)
    op.create_table(
        "bandmembership",
        sa.Column("band_id", sa.Integer(), nullable=False),
        sa.Column("musician_id", sa.Integer(), nullable=False),
        sa.Column(
            "instrument",
            sa.Enum(
                "GUITAR",
                "BASS",
                "DRUMS",
                "VOCALS",
                "KEYBOARD",
                "VIOLIN",
                "SAXOPHONE",
                name="musicinstrument",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["band_id"],
            ["band.id"],
        ),
        sa.ForeignKeyConstraint(
            ["musician_id"],
            ["musician.id"],
        ),
        sa.PrimaryKeyConstraint("band_id", "musician_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bandmembership")
    op.drop_index(op.f("ix_musician_name"), table_name="musician")
    op.drop_table("musician")
    op.drop_index(op.f("ix_band_name"), table_name="band")
    op.drop_table("band")
    # ### end Alembic commands ###
