"""initial

Revision ID: da038a19ed5a
Revises:
Create Date: 2025-10-04 00:52:51.831947

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da038a19ed5a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "band",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("genre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("formed_year", sa.Integer(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_band_name"), "band", ["name"], unique=False)
    op.create_table(
        "musician",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instrument", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("band_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["band_id"],
            ["band.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_musician_name"), "musician", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_musician_name"), table_name="musician")
    op.drop_table("musician")
    op.drop_index(op.f("ix_band_name"), table_name="band")
    op.drop_table("band")
    # ### end Alembic commands ###
